### ISSUE TITLE
[bug] fails to import: removes ports

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetesx#38]
Pulumi does not include ports when adopting resulting in a failure to adopt existing resources:
YAML
```yaml
apiVersion: v1
kind: Service
metadata:
  name: gitea-web
  labels:
    app: gitea-web
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: gitea
```
TS
Not that using the kubernetes package for this service will also fail with a different error.
```ts
import * as kx from '@pulumi/kubernetesx' // version 0.1.1
const svc = new kx.Service(
  'gitea-web',
  {
    metadata: {
      name: 'gitea-web',
      labels: {
        app: 'gitea-web',
      },
    },
    spec: {
      ports: [
        {
          name: 'http',
          port: 80,
          targetPort: 8080,
        },
      ],
      selector: {
        app: GITEA,
      },
    },
  },
  {
    import: 'gitea-web',
    ignoreChanges: ['metadata.annotations'],
  }
)
```

Details:
```
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::gitkit::pulumi:pulumi:Stack::gitkit-dev]
    = kubernetes:core/v1:Service: (import)
        [id=gitea-web]
        [urn=urn:pulumi:dev::gitkit::kubernetes:core/v1:Service::gitea-web]
        [provider=urn:pulumi:dev::gitkit::pulumi:providers:kubernetes::default_1_3_1::3b7c7381-1acb-47d8-a7fd-dd8563b0de39]
      ~ metadata: {
          - annotations: {}
        }
      ~ spec    : {
          ~ ports: [
              - [0]: {
                      - name      : "http"
                      - port      : 80
                      - targetPort: 8080
                    }
            ]
        }
```

Also, I appear to be doing something wrong with getting it to ignore annotations.
