### ISSUE TITLE
[feature] Include default metadata

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetesx#39]
Given that a standard pod starts like this
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
```
and a deployment starts like this
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
```

I would like to see
```ts
new kx.Deployment('name', {
    spec: pod.asDeploymentSpec(),
})
```
default to set the deployment's metadata property to: `{ name: firstArg }`
